piece:
  tonic: C
  scale: major
  n_measures: 32
  max_skip: 2
  line_specifications:
    - species: first
      lowest_note: G3
      highest_note: G4
      start_note: C4
      end_note: C4
    - species: first
      lowest_note: E4
      highest_note: E5
      start_note: C5
      end_note: G4
    - species: first
      lowest_note: G4
      highest_note: G5
      start_note: G5
      end_note: C5
  rendering_params:
    dir: rlmusician_data
    measure_in_seconds: 0.5
    midi:
      instrument: 0
      velocity: 100
    sinethesizer:
      timbre: default_timbre
      volume: 0.2
environment:
  observation_decay: 0.75
  scoring_coefs:
    noncyclicity: 250
    usage_of_tonic: 30
    lines: 1
    conjunct_motion: 2
    contrary_motion: 1
    consonances: 1
    absence_of_outer_notes: 1
    absence_of_stalled_notes: 1
  scoring_fn_params:
    consonances:
      interval_consonances:
        0: 0
        1: -3
        2: -3
        3: 1
        4: 1
        5: 0
        6: -5
        7: 2
        8: 1
        9: 1
        10: -3
        11: -3
      distance_weights:
        0: 1
agent:
  population_size: 150
  elite_fraction: 0.1
  n_episodes_per_candidate: 10
  aggregation_fn: mean
  smoothing_coef: 0.25
  weights_std: 1.0
