piece:
  tonic: C
  scale: major
  n_measures: 32
  max_skip: 2
  line_specifications:
    - lowest_note: G3
      highest_note: G4
      start_note: C4
      end_note: C4
    - lowest_note: E4
      highest_note: E5
      start_note: C5
      end_note: G4
    - lowest_note: G4
      highest_note: G5
      start_note: G5
      end_note: C5
  rendering_params:
    dir: rlmusician_data
    measure_in_seconds: 0.5
    midi:
      instrument: 0
      velocity: 100
    sinethesizer:
      timbre: default_timbre
      volume: 0.2
environment:
  observation_decay: 0.75
  reward_for_dead_end: -100
  scoring_coefs:
    absence_of_unisons: 1
    lines_correlation: 1
  scoring_fn_params: {}
agent:
  hidden_layer_size: 10
crossentropy:
  population_size: 150
  elite_fraction: 0.1
  smoothing_coef: 0.25
  n_episodes_per_candidate: 10
  aggregation_fn: mean
  weights_std: 1.0
