piece:
  tonic: C
  scale: major
  n_measures: 32
  max_skip: 2
  line_specifications:
    - lowest_note: G3
      highest_note: G4
      start_note: C4
      end_note: C4
    - lowest_note: C4
      highest_note: C5
      start_note: G4
      end_note: G4
    - lowest_note: G4
      highest_note: G5
      start_note: G5
      end_note: C5
  rendering_params:
    dir: rlmusician_data
    measure_in_seconds: 0.5
    midi:
      instrument: 0
      velocity: 100
    sinethesizer:
      timbre: default_timbre
      volume: 0.2
environment:
  observation_decay: 0.75
  reward_for_dead_end: -1
  scoring_coefs:
    autocorrelation: 3
    pitch_class_clashes: 2
    entropy: 1
    types_of_motion: 1
    lines_correlation: 1
    climax_explicity: 1
  scoring_fn_params:
    autocorrelation:
      max_lag: 8
    types_of_motion:
      parallel_coef: -1
      similar_coef: -0.5
      oblique_coef: 0
      contrary_coef: 1
    climax_explicity:
      shortage_penalty: 0.3
      duplication_penalty: 0.5
agent:
  hidden_layer_size: 10
  softmax_temperature: 1
crossentropy:
  population_size: 100
  elite_fraction: 0.1
  smoothing_coef: 0.25
  std: 1.0
  n_trials: 10
  aggregation_fn: mean
  parallelling_params:
    n_processes:
    max_tasks_per_child: 1
