environment:
  n_semitones: 13
  n_time_steps: 60
  observed_length: 4
  scoring_coefs:
    note-wise_entropy: 1
    consonances: 1
  scoring_fn_params:
    consonances:
      interval_consonances:
        0: 2
        1: -1
        2: -1
        3: 1
        4: 1
        5: 0
        6: -2
        7: 2
        8: 1
        9: 1
        10: -1
        11: -1
      distance_weights:
        0: 1
        1: 1
        2: 0.5
        3: 0.25
  data_dir: rlmusician_data
